# Generated by Django 6.0.5 on 2026-05-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_remove_skill_years_of_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='address',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='company_website',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='company_name',
            new_name='headline',
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='industry',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='company_size',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='client_covers/'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='client_profiles/'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
